logging:
    path: /user/local/log
    level:
      com:
        favorites: DEBUG
      org:
        springframework:
          web: INFO
        hibernate: ERROR

error:
    whitelabel:
      whitelabel: false

server:
  port: 8086
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
     show-sql: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

